version: '3.9'
services:
  route-delivery:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ../../../.volumes/food-center/sqlserver/:/var/lib/sqlserver/data/
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
